name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pest-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.4]
        laravel: [12.x]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, pdo, sqlite
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Pest Tests
        run: ./vendor/bin/pest
